### ISSUE TITLE
id? prod?

### ISSUE THREAD

**Issue by itssosunny** [DevopsArtFactory/aws-provisioning#21]
Hello, guys.
I have a question.

you mention Id and pro.
```
# Account IDs# Add all account ID to here variable 
"account_id" { 
   default = {    id   = "816736805842"    
                    prod = "002202845208"
  }
}
```

there is my first questions
I think you mean each thing as develop env and production env?

secondly,
In your code, do you recommand to make 2 accounts, which are dev account and production?( not role, not Iam , I mean aws root account)

**Comment by rayleighko** [comment]
hi. This workshop recommends 'multi-account principle'(https://aws.amazon.com/ko/organizations/getting-started/best-practices/). as you asked, a 'mulit-account principle' means using multiple aws accounts(*aws treats them as different accounts when they have the same apex (example.com) but different subdomains (xxx.example.com), so you can manage multiple accounts with one address.)
- you can use or manage multiple accounts through iam assume-role or aws organizations (https://aws.amazon.com/en/organizations/).
- The basics can be found by reading the must-read at this workshop(https://devops-art-factory.gitbook.io/devops-workshop/1.before-workshop/workshop).
